packageExtensions:
  debug@*:
    dependencies:
      supports-color: '*'
  follow-redirects@*:
    dependencies:
      debug: '*'
  pino@*:
    dependencies:
      pino-pretty: '*'
  ws@*:
    dependencies:
      bufferutil: '*'
      utf-8-validate: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  '@monstrs/prettier-typescript-plugin@*':
    dependencies:
      prettier: '*'

yarnPath: .yarn/releases/yarn.js
