packageExtensions:
  '@monstrs/prettier-typescript-plugin@*':
    dependencies:
      prettier: '*'
  debug@*:
    dependencies:
      supports-color: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  follow-redirects@*:
    dependencies:
      debug: '*'
  pino@*:
    dependencies:
      pino-pretty: '*'
  ws@*:
    dependencies:
      bufferutil: '*'
      utf-8-validate: '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20220123.hash-e164fa25.cjs
