packageExtensions:
  debug@*:
    dependencies:
      supports-color: '*'
  follow-redirects@*:
    dependencies:
      debug: '*'
  pino@*:
    dependencies:
      pino-pretty: '*'
  ws@*:
    dependencies:
      bufferutil: '*'
      utf-8-validate: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - .yarn/plugins/@monstrs/plugin-essentials.cjs

yarnPath: .yarn/releases/yarn-2.4.1.cjs
