---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: previewversions.preview.monstrs.tech
spec:
  group: preview.monstrs.tech
  names:
    kind: PreviewVersion
    listKind: PreviewVersionList
    plural: previewversions
    singular: previewversion
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: PreviewVersion is the Schema for the previewversions API
          properties:
            spec:
              properties:
                tag:
                  type: string
                previewAutomationRef:
                  properties:
                    name:
                      type: string
                  type: object
                scope:
                  properties:
                    id:
                      type: string
                  type: object
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ''
    plural: ''
  conditions: []
  storedVersions: []
