apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: preview-image-reflector-operator-test
  name: preview-image-reflector-operator-test
  namespace: default
spec:
  selector:
    matchLabels:
      app: preview-image-reflector-operator-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: preview-image-reflector-operator-test
    spec:
      containers:
        - image: monstrs/preview-operator-test-image:latest
          imagePullPolicy: Always
          name: preview-operator-test
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
