---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: previewautomations.preview.monstrs.tech
spec:
  group: preview.monstrs.tech
  names:
    kind: PreviewAutomation
    listKind: PreviewAutomationList
    plural: previewautomations
    singular: previewautomation
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: PreviewAutomation is the Schema for the previewautomations API
          properties:
            spec:
              properties:
                endpointRef:
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                  type: object
                imageRepositoryRef:
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                  type: object
                sourceRef:
                  properties:
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                  type: object
                endpoint:
                  properties:
                    domain:
                      type: string
                  type: object
                resources:
                  description: Resources refers to kubernetes resources subject to kustomization.
                  items:
                    description: Selector specifies a set of resources. Any resource that
                      matches intersection of all conditions is included in this set.
                    properties:
                      annotationSelector:
                        description: AnnotationSelector is a string that follows the label
                          selection expression https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#api
                          It matches with the resource annotations.
                        type: string
                      group:
                        type: string
                      kind:
                        type: string
                      labelSelector:
                        description: LabelSelector is a string that follows the label
                          selection expression https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#api
                          It matches with the resource labels.
                        type: string
                      name:
                        type: string
                      namespace:
                        type: string
                      version:
                        type: string
                    type: object
                  type: array
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ''
    plural: ''
  conditions: []
  storedVersions: []
