---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: previewendpoints.preview.monstrs.tech
spec:
  group: preview.monstrs.tech
  names:
    kind: PreviewEndpoint
    listKind: PreviewEndpointList
    plural: previewendpoints
    singular: previewendpoint
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: PreviewEndpoint is the Schema for the previewendpoints API
          properties:
            spec:
              properties:
                url:
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ''
    plural: ''
  conditions: []
  storedVersions: []
