apiVersion: v1
kind: Service
metadata:
  name: preview-pull-request-sync-operator-test
  labels:
    app: preview-pull-request-sync-operator-test
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: preview-pull-request-sync-operator-test
