name: Checks

on: [pull_request]

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.10'

      - uses: AbsaOSS/k3d-action@v1.3.1
        name: 'Create k3d cluster'
        with:
          cluster-name: 'test'

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn checks lint
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: TypeCheck
        run: yarn checks typecheck
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: TestUnit
        run: yarn checks test unit
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: TestIntegration
        run: yarn checks test integration
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Release
        run: yarn checks release
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
